### ISSUE TITLE
KIS breaks Werner Checker after loading vessel

### ISSUE THREAD

**Issue by Divstator** [linuxgurugamer/WernherChecker#6]
To repeat bug:
In the editor, save a command module with a KIS screwdriver in seat inventory. Exit editor. Re-enter editor and load command vessel with screwdriver in inventory. Checklist works until it gets to KIS checklist item. Anything below KIS checklist item is unresponsive. Command module shows false even though KIS item shows true in the command module. If screwdriver is removed from seat inventory of the command module, then bug goes away. Also, while bug is in place, modifications to the "settings" menu outside the VAB will not apply. Current fixes are to either remove KIS items from seat inventory before saving or after vehicle is loaded into the editor, change KIS seat inventory or to make KIS checklist item the last before manual checklist items in the cfg file. Manual checklist items are unaffected by this bug. However, if "making KIS checklist item the last before manual list items" is used, the "settings" bug remains in place as this fix is only cosmetic. I have looked at the C# code but so far have been unsuccessful in locating the problem.

**Comment by davedev** [comment]
Just experienced the same issue.  I pulled these relevant entries from the log.  I'd usually attach the full ksp.log file too but, my log is over 90MB right now... github says "no thanks" XD

[ERR 13:28:23.640] Exception handling event onEditorShipModified in class ChecklistSystem:System.NullReferenceException: Object reference not set to an instance of an object
  at WernherChecker.ChecklistSystem.CheckForKISModules (WernherChecker.Criterion crton) [0x00000] in <filename unknown>:0 
  at WernherChecker.ChecklistSystem.CheckForModules (WernherChecker.Criterion crton) [0x00000] in <filename unknown>:0 
  at WernherChecker.ChecklistSystem.CheckVessel (.ShipConstruct ship) [0x00000] in <filename unknown>:0 
  at EventData`1[ShipConstruct].Fire (.ShipConstruct data) [0x00000] in <filename unknown>:0 

[EXC 13:28:23.641] NullReferenceException: Object reference not set to an instance of an object
	WernherChecker.ChecklistSystem.CheckForKISModules (WernherChecker.Criterion crton)
	WernherChecker.ChecklistSystem.CheckForModules (WernherChecker.Criterion crton)
	WernherChecker.ChecklistSystem.CheckVessel (.ShipConstruct ship)
	EventData`1[ShipConstruct].Fire (.ShipConstruct data)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(ShipConstruct)
	EditorLogic:SetBackup()
	EditorLogic:<SetupFSM>m__27()
	KerbalFSM:RunEvent(KFSMEvent)
	KerbalFSM:updateFSM(KFSMUpdateMode)
	KerbalFSM:UpdateFSM()
	EditorLogic:Update()

[ERR 13:28:23.642] Exception handling event onEditorShipModified in class ChecklistSystem:System.NullReferenceException: Object reference not set to an instance of an object
  at WernherChecker.ChecklistSystem.CheckForKISModules (WernherChecker.Criterion crton) [0x00000] in <filename unknown>:0 
  at WernherChecker.ChecklistSystem.CheckForModules (WernherChecker.Criterion crton) [0x00000] in <filename unknown>:0 
  at WernherChecker.ChecklistSystem.CheckVessel (.ShipConstruct ship) [0x00000] in <filename unknown>:0 
  at EventData`1[ShipConstruct].Fire (.ShipConstruct data) [0x00000] in <filename unknown>:0 

[EXC 13:28:23.642] NullReferenceException: Object reference not set to an instance of an object
	WernherChecker.ChecklistSystem.CheckForKISModules (WernherChecker.Criterion crton)
	WernherChecker.ChecklistSystem.CheckForModules (WernherChecker.Criterion crton)
	WernherChecker.ChecklistSystem.CheckVessel (.ShipConstruct ship)
	EventData`1[ShipConstruct].Fire (.ShipConstruct data)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(ShipConstruct)
	EditorLogic:SetBackup()
	EditorLogic:<SetupFSM>m__27()
	KerbalFSM:RunEvent(KFSMEvent)
	KerbalFSM:updateFSM(KFSMUpdateMode)
	KerbalFSM:UpdateFSM()
	EditorLogic:Update()

[ERR 13:28:23.642] Exception handling event onEditorShipModified in class ChecklistSystem:System.NullReferenceException: Object reference not set to an instance of an object
  at WernherChecker.ChecklistSystem.CheckForKISModules (WernherChecker.Criterion crton) [0x00000] in <filename unknown>:0 
  at WernherChecker.ChecklistSystem.CheckForModules (WernherChecker.Criterion crton) [0x00000] in <filename unknown>:0 
  at WernherChecker.ChecklistSystem.CheckVessel (.ShipConstruct ship) [0x00000] in <filename unknown>:0 
  at EventData`1[ShipConstruct].Fire (.ShipConstruct data) [0x00000] in <filename unknown>:0 


[EXC 13:28:23.643] NullReferenceException: Object reference not set to an instance of an object
	WernherChecker.ChecklistSystem.CheckForKISModules (WernherChecker.Criterion crton)
	WernherChecker.ChecklistSystem.CheckForModules (WernherChecker.Criterion crton)
	WernherChecker.ChecklistSystem.CheckVessel (.ShipConstruct ship)
	EventData`1[ShipConstruct].Fire (.ShipConstruct data)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(ShipConstruct)
	EditorLogic:SetBackup()
	EditorLogic:<SetupFSM>m__27()
	KerbalFSM:RunEvent(KFSMEvent)
	KerbalFSM:updateFSM(KFSMUpdateMode)
	KerbalFSM:UpdateFSM()
	EditorLogic:Update()

**Comment by linuxgurugamer** [comment]
Please zip up the log, and if it's still too big, put it on a filesharing site somewhere and provide the link.

**Comment by linuxgurugamer** [comment]
Closing this due to no response
